apiVersion: v1
kind: Secret
metadata:
  name: django-app-repo
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: repository
type: Opaque
stringData:
  url: ${django_app_repo}
  type: git
  password: ""
  username: not-used
