apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "django-app.fullname" . }}-config
  labels:
    {{- include "django-app.labels" . | nindent 4 }}
data:
  DEBUG: "False"
  ALLOWED_HOSTS: "localhost,127.0.0.1,django-app.local"
  DATABASE_ENGINE: "django.db.backends.postgresql"
  DATABASE_HOST: "postgres.default.svc.cluster.local"
  DATABASE_PORT: "5432"
  DATABASE_NAME: "django_db"
  LOG_LEVEL: "INFO"
  PYTHONUNBUFFERED: "1"
